import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from '@/components/Footer '
import Nav from '@/components/Nav '

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Nav />
        <div className=" 
        bg-[url('https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D')]
          flex flex-col mx-auto  min-h-screen items-center justify-between p-24 text-white ">
 {children}
        </div>
        <Footer />
 </body>
    </html>
  );
}
